---

- name: install dependancies
  apt: name={{ item }}
       state=latest
       update_cache=yes
  with_items:
    - apache2
  tags:
    - install
  sudo: yes

- name: copy config files
  template: src={{ item.src }}
            dest=/etc/apache2/{{ item.dest }}
  with_items:
    - { src: apache2.conf.j2, dest: apache2.conf }
    - { src: app.conf.j2, dest: "sites-available/000.{{ server_name }}.conf" }
  sudo: yes

- name: create document root
  file: dest={{ document_root }}
        owner={{ document_owner }}
        group={{ document_group }}
        state=directory
  sudo: yes

- name: deactivate default domain
  raw: a2dissite {{ item }}
  with_items:
    - 000-default
  sudo: yes

- name: activate domain
  raw: a2ensite {{ item }}
  with_items:
    - "000.{{ server_name }}.conf"
  notify: start apache2
  sudo: yes
