---

- name: install dependancies
  apt: name={{ item }}
       state=latest
       update_cache=yes
  with_items:
    - apache2
  notify: start apache2
  tags:
    - install
  sudo: yes

- name: debug apache
  raw: apache2ctl -V
  sudo: yes
  register: dbv

- debug: var=dbv

- name: create self-signed ssl certificate
  raw: 'openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/{{ ssl_key }} -out /etc/ssl/certs/{{ ssl_crt }} -subj "/C=US/ST=./L=./O=./OU=./CN={{ server_name }}"'
  when: SELF_SIGNED and SSL
  sudo: yes

- name: enable ssl module
  apache2_module: name={{ item }}
                  state=present
  with_items:
    - ssl
  sudo: yes

- name: copy config files
  template: src={{ item.src }}
            dest=/etc/apache2/{{ item.dest }}
  with_items:
    - { src: apache2.2.2.conf.j2, dest: apache2.conf }
    - { src: app.2.2.conf.j2, dest: "sites-available/000.{{ server_name }}.conf" }
    - { src: ports.conf.j2, dest: ports.conf }
  sudo: yes
  when: ansible_distribution == 'Ubuntu' and
        ansible_distribution_version == '12.04'

- name: create document root
  file: dest={{ document_root }}
        owner={{ document_owner }}
        group={{ document_group }}
        state=directory
  sudo: yes

- name: deactivate default domain
  raw: a2dissite {{ item }}
  with_items:
    - 000-default
  sudo: yes

- name: activate domain
  raw: a2ensite {{ item }}
  with_items:
    - "000.{{ server_name }}.conf"
  sudo: yes

- name: restart apache2
  service: name=apache2
           state=restarted
